name: Build OrcaSlicer macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Find build scripts
        run: find . -name "*.sh"
