name: Build OrcaSlicer macOS

on:
  workflow_dispatch:

jobs:
 build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build OrcaSlicer
        run: |
          chmod +x build_release_macos.sh
          ./build_release_macos.sh
